javax:
  sql:
    DataSource:
      postgres:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost/postgres # update your connection string
          user: sbutta # update your credentials
          password: "" # update your password

openai:
  endpoint: https://api.openai.com/v1
  token: "your-token"

# it allows all - needs to be updated for production setup
cors:
  paths:
    - path-pattern: "*"
      allow-methods: "*"
      allow-origins: "*"